# Generated by Django 6.0 on 2025-12-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegetarian',
            new_name='nonVeg',
        ),
    ]
