# Generated by Django 6.0 on 2026-01-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_adminactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
