# Generated by Django 6.0 on 2026-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'area')},
        ),
    ]
