# Generated by Django 6.0 on 2026-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_restaurant_area_alter_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
